server:
  port: 5432
spring:
  datasource:
    url: jdbc:postgresql://ec2-54-80-122-11.compute-1.amazonaws.com:5432/d6lj1p7p2rphc1
    username: jxpjsszldjvego
    password: 1155c686cf9c0e02e58884486700bcd0920f83b4a6162d4c8cd9cde1260cfdd5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: base
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: akunmainan2001@gmail.com
    password: fysbudnfpgyzjsbp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
    protocol: smtp
    test-connection: false
